/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import models.Doctor;

/**
 *
 * @author shreyasisodiya
 */
public class CreateDoctor extends javax.swing.JFrame {

    /**
     * Creates new form CreateDoctor
     */
    public CreateDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textDocFName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textDocLName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboDocGender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        textDocUserName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboDocCIty = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        comboDocComm = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        comboDocHouse = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        comboDocPin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboDocHospitalName = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboDocPassword = new javax.swing.JPasswordField();
        buttondocSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("DOCTOR");

        jLabel2.setText("NAME");

        textDocFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDocFNameActionPerformed(evt);
            }
        });

        jLabel3.setText("LAST NAME");

        textDocLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDocLNameActionPerformed(evt);
            }
        });

        jLabel4.setText("GENDER");

        comboDocGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT ONE", "FEMALE", "MALE", "TRANSGENDER", "NON BINARY", "OTHER" }));

        jLabel5.setText("USER NAME");

        textDocUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDocUserNameActionPerformed(evt);
            }
        });

        jLabel6.setText("CITY");

        comboDocCIty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CITY" }));
        comboDocCIty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDocCItyActionPerformed(evt);
            }
        });

        jLabel7.setText("COMMUNITY ");

        comboDocComm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMMUNITY", " " }));
        comboDocComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDocCommActionPerformed(evt);
            }
        });

        jLabel8.setText("HOUSE");

        comboDocHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDocHouseActionPerformed(evt);
            }
        });

        jLabel9.setText("PIN CODE");

        comboDocPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDocPinActionPerformed(evt);
            }
        });

        jLabel10.setText("HOSPITAL NAME");

        comboDocHospitalName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOSPITAL NAME", " " }));

        jLabel11.setText("SET PASSWORD");

        comboDocPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDocPasswordActionPerformed(evt);
            }
        });

        buttondocSave.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        buttondocSave.setText("SAVE");
        buttondocSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondocSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboDocPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textDocFName)
                            .addComponent(comboDocGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboDocCIty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboDocHouse)
                            .addComponent(comboDocHospitalName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addGap(43, 43, 43)
                                .addComponent(textDocLName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(25, 25, 25))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboDocPin)
                                    .addComponent(comboDocComm, 0, 135, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textDocUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(buttondocSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDocFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDocLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textDocUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDocGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDocCIty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(comboDocComm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(comboDocHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(comboDocPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboDocHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comboDocPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(buttondocSave)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textDocFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDocFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDocFNameActionPerformed

    private void textDocLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDocLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDocLNameActionPerformed

    private void textDocUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDocUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDocUserNameActionPerformed

    private void comboDocCItyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDocCItyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDocCItyActionPerformed

    private void comboDocCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDocCommActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDocCommActionPerformed

    private void comboDocHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDocHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDocHouseActionPerformed

    private void comboDocPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDocPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDocPinActionPerformed

    private void comboDocPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDocPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDocPasswordActionPerformed

    private void buttondocSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondocSaveActionPerformed
        // TODO add your handling code here:
        //Doctor doc = new Doctor(comboHospitalName.getSelectedItem().toString(),text);

        //
        //        if(textName.getText().equals("") || textEmployeeID.getText().equals("")|| textAge.getText().equals("")
            //                || textStartDate.getText().equals("") || textLevel.getText().equals("") || textTeamInfo.getText().equals("")
            //                || textPositionTitle.getText().equals("") || textPhone.getText().equals("") || textEmail.getText().equals("")
            //                || textGender.getText().equals(""))
        //        {
            //            JOptionPane.showMessageDialog(this, "Do Not Leave Any Field Blank");
            //        }
        //        else if(!(Pattern.matches("^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$", textEmail.getText())))
        //        {
            //            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            //        }
        //        else
        //        {
            //            String empData[] = {textName.getText(),textEmployeeID.getText(), textAge.getText(), textGender.getText() ,
                //                textStartDate.getText(), textLevel.getText(), textTeamInfo.getText(), textPositionTitle.getText(),
                //                textPhone.getText(), textEmail.getText(), imgPath};
            //
            //            DefaultTableModel defTable = (DefaultTableModel)tableEmployee.getModel();
            //            defTable.addRow(empData);
            //
            //            ImageIcon ii = new ImageIcon(imgPath);
            //
            //            JOptionPane.showMessageDialog(this,"Employee Data Saved");
            //
            //            textName.setText("");
            //            textEmployeeID.setText("");
            //            textAge.setText("");
            //            textGender.setText("");
            //            textStartDate.setText("");
            //            textLevel.setText("");
            //            textTeamInfo.setText("");
            //            textPositionTitle.setText("");
            //            textPhone.setText("");
            //            textEmail.setText("");
            //            labelImage.setVisible(false);
            //            labelImage.setIcon(null);
            //        }
    }//GEN-LAST:event_buttondocSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttondocSave;
    private javax.swing.JComboBox<String> comboDocCIty;
    private javax.swing.JComboBox<String> comboDocComm;
    private javax.swing.JComboBox<String> comboDocGender;
    private javax.swing.JComboBox<String> comboDocHospitalName;
    private javax.swing.JTextField comboDocHouse;
    private javax.swing.JPasswordField comboDocPassword;
    private javax.swing.JTextField comboDocPin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textDocFName;
    private javax.swing.JTextField textDocLName;
    private javax.swing.JTextField textDocUserName;
    // End of variables declaration//GEN-END:variables
}
