/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import static medical_resource_management.MEDICAL_RESOURCE_MANAGEMENT.communityAdminMap;
import static medical_resource_management.MEDICAL_RESOURCE_MANAGEMENT.doctorMap;
import static medical_resource_management.MEDICAL_RESOURCE_MANAGEMENT.patientMap;
import models.CommunityAdmin;
import models.Doctor;
import models.Patient;

/**
 *
 * @author shreyasisodiya
 */
public class ManageUsers extends javax.swing.JFrame {

    /**
     * Creates new form ManageUsers
     */
    public ManageUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPatientType = new javax.swing.JButton();
        buttonDoctorType = new javax.swing.JButton();
        buttonCommAdminType = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonBackUserType = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonPatientType.setText("PATIENT");
        buttonPatientType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPatientTypeActionPerformed(evt);
            }
        });

        buttonDoctorType.setText("DOCTOR");
        buttonDoctorType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDoctorTypeActionPerformed(evt);
            }
        });

        buttonCommAdminType.setText("COMMUNITY ADMIN");
        buttonCommAdminType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCommAdminTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("SELECT USER TYPE");

        buttonBackUserType.setText("BACK");
        buttonBackUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackUserTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonBackUserType)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonPatientType)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonDoctorType)
                                .addGap(40, 40, 40)
                                .addComponent(buttonCommAdminType))
                            .addComponent(jLabel1))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDoctorType)
                    .addComponent(buttonPatientType)
                    .addComponent(buttonCommAdminType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(buttonBackUserType)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPatientTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPatientTypeActionPerformed
        // TODO add your handling code here:
        ViewInfo view = new ViewInfo();
        view.labelTableDisplay.setText("Patients");
        String[] columnNames = {"Patient Name", "Community", "City"};
        String[][] rows = new String[patientMap.size()][3];
        int i = 0;
        for (HashMap.Entry<String, Patient> set : patientMap.entrySet()) {
            //rows[i][0] = set.getValue().getPatientID();
            rows[i][0] = set.getValue().getFirstName();
            rows[i][1] = set.getValue().getCommunityName();
            rows[i][2] = set.getValue().getCityName();
            i++;
        }
        DefaultTableModel dtm = new DefaultTableModel (rows, columnNames);
        view.tableDisplay.setModel(dtm);
        view.show();       
    }//GEN-LAST:event_buttonPatientTypeActionPerformed

    private void buttonBackUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackUserTypeActionPerformed
        // TODO add your handling code here:
        this.hide();
        ViewSystemAdmin vsa = new ViewSystemAdmin();
        vsa.show();
    }//GEN-LAST:event_buttonBackUserTypeActionPerformed

    private void buttonDoctorTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDoctorTypeActionPerformed
        // TODO add your handling code here:
        ViewInfo view = new ViewInfo();
        view.labelTableDisplay.setText("Doctors");
        String[] columnNames = {"Name", "Hospital Name", "Community", "City"};
        String[][] rows = new String[doctorMap.size()][4];

        int i = 0;
        for (HashMap.Entry<String, Doctor> set : doctorMap.entrySet()) {
            rows[i][0] = set.getValue().getFirstName();
            rows[i][1] = set.getValue().getHospitalName();
            rows[i][2] = set.getValue().getCityName();
            rows[i][3] = set.getValue().getCommunityName();
            
            i++;
        }

        DefaultTableModel dtm = new DefaultTableModel (rows, columnNames);
        view.tableDisplay.setModel(dtm);
        view.show();
    }//GEN-LAST:event_buttonDoctorTypeActionPerformed

    private void buttonCommAdminTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCommAdminTypeActionPerformed
        // TODO add your handling code here:
        ViewInfo view = new ViewInfo();
        view.labelTableDisplay.setText("Community Admin");
        String[] columnNames = {"Name", "Community", "City"};
        String[][] rows = new String[communityAdminMap.size()][3];

        int i = 0;
        for (HashMap.Entry<String, CommunityAdmin> set : communityAdminMap.entrySet()) {
            rows[i][0] = set.getValue().getUserName();
            rows[i][1] = set.getValue().getCommunityName();
            rows[i][2] = set.getValue().getCityName();            
            i++;
        }

        DefaultTableModel dtm = new DefaultTableModel (rows, columnNames);
        view.tableDisplay.setModel(dtm);
        view.show();
    }//GEN-LAST:event_buttonCommAdminTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBackUserType;
    private javax.swing.JButton buttonCommAdminType;
    private javax.swing.JButton buttonDoctorType;
    private javax.swing.JButton buttonPatientType;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
